// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/account-type.ts.
// spell-checker: disable

export const data = {
	"emailAccount": {
		"labels": [
			"Apple",
			"Google",
			"Microsoft",
			"Other"
		],
		"data": {
			"Compromised": {
				"Original": [
					0,
					1,
					0,
					0
				],
				"Revised": [
					0,
					1,
					0,
					0
				],
				"Not Worst": [
					0,
					1,
					0,
					0
				]
			},
			"Locked Out": {
				"Original": [
					0,
					2,
					0,
					0
				],
				"Revised": [
					0,
					1,
					0,
					0
				],
				"Not Worst": [
					0,
					0,
					1,
					1
				]
			}
		}
	},
	"socialAccount": {
		"labels": [
			"Facebook",
			"Instagram",
			"Twitter/X",
			"SnapChat",
			"WhatsApp",
			"WeChat",
			"Signal",
			"Other"
		],
		"data": {
			"Compromised": {
				"Original": [
					1,
					0,
					0,
					0,
					0,
					0,
					0,
					2
				],
				"Revised": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"Not Worst": [
					1,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				]
			},
			"Locked Out": {
				"Original": [
					1,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"Revised": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"Not Worst": [
					3,
					0,
					1,
					1,
					0,
					0,
					0,
					0
				]
			}
		}
	},
	"financialAccount": {
		"labels": [
			"Credit Card",
			"Credit Union",
			"Retirement",
			"Brokerage",
			"Paypal",
			"Venmo",
			"Cryptocurrency",
			"Bank",
			"Other"
		],
		"data": {
			"Compromised": {
				"Original": [
					0,
					0,
					0,
					0,
					2,
					0,
					0,
					3,
					0
				],
				"Revised": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"Not Worst": [
					1,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				]
			},
			"Locked Out": {
				"Original": [
					0,
					0,
					0,
					0,
					1,
					0,
					0,
					2,
					0
				],
				"Revised": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"Not Worst": [
					0,
					0,
					0,
					0,
					0,
					0,
					1,
					6,
					0
				]
			}
		}
	}
};
