// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/age.ts.
// spell-checker: disable

export const data = [
	{
		"x": 30,
		"y": 5
	},
	{
		"x": 30,
		"y": 5
	},
	{
		"x": 27,
		"y": 6
	},
	{
		"x": 35,
		"y": 2
	},
	{
		"x": 57,
		"y": 4
	},
	{
		"x": 47,
		"y": 4
	},
	{
		"x": 21,
		"y": 1
	},
	{
		"x": 58,
		"y": 4
	},
	{
		"x": 39,
		"y": 2
	},
	{
		"x": 60,
		"y": 4
	},
	{
		"x": 23,
		"y": 5
	},
	{
		"x": 40,
		"y": 1
	},
	{
		"x": 26,
		"y": 2
	},
	{
		"x": 26,
		"y": 0
	},
	{
		"x": 44,
		"y": 13
	},
	{
		"x": 23,
		"y": 7
	},
	{
		"x": 39,
		"y": 6
	},
	{
		"x": 51,
		"y": 4
	},
	{
		"x": 37,
		"y": 2
	},
	{
		"x": 33,
		"y": 3
	}
] as const;
