// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/harm-focused-likert.ts.
// spell-checker: disable

	export const labels = [
	"Lost Photos",
	"Lost Emails",
	"Mental Health"
];
	export const counts = {
	"1": [
		0,
		0,
		0
	],
	"2": [
		1,
		1,
		0
	],
	"3": [
		0,
		2,
		0
	],
	"4": [
		3,
		1,
		0
	],
	"5": [
		4,
		3,
		0
	],
	"6": [
		2,
		0,
		0
	],
	"7": [
		5,
		1,
		0
	],
	"No loss": [
		0,
		0,
		0
	]
};
	export const percentsOfResponses = {
	"1": [
		0,
		0,
		0
	],
	"2": [
		5,
		5,
		0
	],
	"3": [
		0,
		10,
		0
	],
	"4": [
		15,
		5,
		0
	],
	"5": [
		20,
		15,
		0
	],
	"6": [
		10,
		0,
		0
	],
	"7": [
		25,
		5,
		0
	],
	"No loss": [
		0,
		0,
		0
	]
};
	export const percentsOfAnswered = {
	"1": [
		0,
		0,
		0
	],
	"2": [
		6.666666666666667,
		12.5,
		0
	],
	"3": [
		0,
		25,
		0
	],
	"4": [
		20,
		12.5,
		0
	],
	"5": [
		26.666666666666668,
		37.5,
		0
	],
	"6": [
		13.333333333333334,
		0,
		0
	],
	"7": [
		33.333333333333336,
		12.5,
		0
	],
	"No loss": [
		0,
		0,
		0
	]
};
