// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/harm-focused-likert.ts.
// spell-checker: disable

	export const labels = [
	"Lost Photos",
	"Lost Emails"
];
	export const counts = {
	"1": [
		0,
		0
	],
	"2": [
		0,
		1
	],
	"3": [
		0,
		1
	],
	"4": [
		1,
		1
	],
	"5": [
		3,
		1
	],
	"6": [
		1,
		0
	],
	"7": [
		2,
		0
	],
	"No loss": [
		0,
		0
	]
};
	export const percentsOfResponses = {
	"1": [
		0,
		0
	],
	"2": [
		0,
		10
	],
	"3": [
		0,
		10
	],
	"4": [
		10,
		10
	],
	"5": [
		30,
		10
	],
	"6": [
		10,
		0
	],
	"7": [
		20,
		0
	],
	"No loss": [
		0,
		0
	]
};
	export const percentsOfAnswered = {
	"1": [
		0,
		0
	],
	"2": [
		0,
		25
	],
	"3": [
		0,
		25
	],
	"4": [
		14.285714285714286,
		25
	],
	"5": [
		42.857142857142854,
		25
	],
	"6": [
		14.285714285714286,
		0
	],
	"7": [
		28.571428571428573,
		0
	],
	"No loss": [
		0,
		0
	]
};
