// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.
// spell-checker: disable

export const pairedScenarioLabels = [
	"Device",
	"Account",
	"Social",
	"Bank",
	"Passwords"
];
export const compromisedScenarioData = {
	"Original": [
		10,
		5,
		15,
		25,
		10
	],
	"Revised": [
		5,
		5,
		0,
		0,
		0
	],
	"Not Worst": [
		25,
		5,
		5,
		5,
		5
	],
	"Could Happen": [
		55,
		60,
		55,
		60,
		60
	],
	"Impossible": [
		5,
		25,
		25,
		10,
		25
	]
};
export const lockedOutScenarioData = {
	"Original": [
		5,
		10,
		5,
		15,
		5
	],
	"Revised": [
		5,
		5,
		0,
		0,
		5
	],
	"Not Worst": [
		15,
		15,
		25,
		35,
		20
	],
	"Could Happen": [
		55,
		40,
		45,
		40,
		45
	],
	"Impossible": [
		20,
		30,
		25,
		10,
		25
	]
};
export const unpairedScenarioLabels = [
	"Replaced Device/OS",
	"Broken Promise",
	"Abuse",
	"Lost Photos",
	"Lost Emails",
	"Mental Health"
];
export const unpairedScenarioData = {
	"Original": [
		10,
		20,
		20,
		35,
		10.526315789473685,
		0
	],
	"Revised": [
		0,
		5,
		0,
		10,
		5.2631578947368425,
		0
	],
	"Not Worst": [
		25,
		25,
		10,
		30,
		21.05263157894737,
		0
	],
	"Could Happen": [
		50,
		45,
		50,
		20,
		15.789473684210526,
		0
	],
	"Impossible": [
		15,
		5,
		20,
		5,
		47.36842105263158,
		0
	]
};
export const compromisedAndUnpairedScenarioData = {
	"Original": [
		10,
		5,
		15,
		25,
		10,
		10,
		20,
		20,
		35,
		10.526315789473685,
		0
	],
	"Revised": [
		5,
		5,
		0,
		0,
		0,
		0,
		5,
		0,
		10,
		5.2631578947368425,
		0
	],
	"Not Worst": [
		25,
		5,
		5,
		5,
		5,
		25,
		25,
		10,
		30,
		21.05263157894737,
		0
	],
	"Could Happen": [
		55,
		60,
		55,
		60,
		60,
		50,
		45,
		50,
		20,
		15.789473684210526,
		0
	],
	"Impossible": [
		5,
		25,
		25,
		10,
		25,
		15,
		5,
		20,
		5,
		47.36842105263158,
		0
	]
};