// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.
// spell-checker: disable

export const pairedScenarioLabels = [
	"Device",
	"Account",
	"Social",
	"Bank",
	"Passwords"
];
export const compromisedScenarioData = {
	"Original": [
		0,
		0,
		10,
		30,
		10
	],
	"Added": [
		0,
		0,
		0,
		0,
		0
	],
	"Not Worst": [
		30,
		10,
		10,
		10,
		0
	],
	"Could Happen": [
		60,
		50,
		40,
		40,
		50
	],
	"Impossible": [
		10,
		40,
		40,
		20,
		40
	]
};
export const lockedOutScenarioData = {
	"Original": [
		0,
		10,
		0,
		20,
		0
	],
	"Added": [
		0,
		0,
		0,
		0,
		10
	],
	"Not Worst": [
		20,
		10,
		20,
		40,
		20
	],
	"Could Happen": [
		50,
		30,
		50,
		30,
		20
	],
	"Impossible": [
		30,
		50,
		30,
		10,
		50
	]
};
export const unpairedScenarioLabels = [
	"Replaced Device/OS",
	"Broken Promise",
	"Abuse"
];
export const unpairedScenarioData = {
	"Original": [
		10,
		30,
		10
	],
	"Added": [
		0,
		0,
		0
	],
	"Not Worst": [
		20,
		20,
		20
	],
	"Could Happen": [
		60,
		50,
		50
	],
	"Impossible": [
		10,
		0,
		20
	]
};
export const compromisedAndUnpairedScenarioData = {
	"Original": [
		0,
		0,
		10,
		30,
		10,
		10,
		30,
		10
	],
	"Added": [
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0
	],
	"Not Worst": [
		30,
		10,
		10,
		10,
		0,
		20,
		20,
		20
	],
	"Could Happen": [
		60,
		50,
		40,
		40,
		50,
		60,
		50,
		50
	],
	"Impossible": [
		10,
		40,
		40,
		20,
		40,
		10,
		0,
		20
	]
};