title: The Unmeasured Human Costs of Security Technology
description: A joint research project between the University of California at Berkeley and Harvard University.
author:
  name: The UHCoS Team,
  email: youremailaddress@example.com,
  url: https://hiddenhumancosts.org/about-me/
