title: The Unmeasured Harms of Technology
description: A joint research project between the University of California at Berkeley and Harvard University.
author:
  name: The Unmeasured Harms Team,
  email: team@uharm.org,
  url: https://uharm.org/
