import { AugmentedSurveyResponses } from "../SurveyResponse.ts";

export const generateSummaryStatistics = (outPath: string, responses: AugmentedSurveyResponses) => {
		const data = {
			numberOfParticipants: responses.length,
		}
    Deno.writeTextFileSync(`${outPath}/data.ts`, `// Automatically generated by summary-statistics.ts.${"\n"}// EXPECT MODIFICATIONS TO BE OVERWRITTEN.${"\n\n"
			}export const data = ${JSON.stringify(data, undefined, "\t")} as const;`);
  }
;
