// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by graph-data/device-bar-chart.ts.

export const labels = [
	"iPhone",
	"Android Phone",
	"Other Phone",
	"iPad",
	"Android Tablet",
	"Other Tablet",
	"Mac",
	"Windows",
	"UNIX",
	"Other Computer"
];
export const data = {
	"hacked": [
		5,
		8,
		0,
		1,
		0,
		1,
		0,
		5,
		0,
		0
	],
	"locked": [
		4,
		7,
		0,
		0,
		0,
		0,
		1,
		2,
		0,
		0
	]
} as const;