// Automatically generated by device-bar-chart.ts.
// EXPECT MODIFICATIONS TO BE OVERWRITTEN.

export const labels = [
	"iPhone",
	"Android Phone",
	"Other Phone",
	"iPad",
	"Android Tablet",
	"Other Tablet",
	"Mac",
	"Windows",
	"UNIX",
	"Other Computer"
];
export const data = {
	"hacked": [
		3,
		5,
		0,
		0,
		0,
		1,
		0,
		2,
		0,
		0
	],
	"locked": [
		2,
		2,
		0,
		0,
		0,
		0,
		1,
		1,
		0,
		0
	]
} as const;