// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by graph-data/scenario-recency.ts.

export const labels = [
	"Hacked Device",
	"Locked Device",
	"Hacked Account",
	"Locked Account",
	"Hacked Social",
	"Locked Social",
	"Hacked Financial",
	"Locked Financial",
	"Hacked Passwords",
	"Locked Passwords"
];
export const absoluteData = {
	"Within Year": [
		8,
		3,
		2,
		3,
		3,
		3,
		1,
		3,
		0,
		3
	],
	"1-3 Years": [
		5,
		4,
		3,
		10,
		4,
		3,
		4,
		1,
		3,
		1
	],
	"3-5 Years": [
		4,
		4,
		2,
		3,
		5,
		1,
		6,
		2,
		1,
		0
	],
	"5-10 Years": [
		6,
		2,
		2,
		2,
		4,
		1,
		0,
		0,
		1,
		2
	],
	"> 10 years": [
		1,
		1,
		1,
		2,
		1,
		0,
		1,
		0,
		0,
		0
	],
	"other": [
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0
	]
} as const;
export const percentData = {
	"Within Year": [
		33.333333333333336,
		21.428571428571427,
		20,
		15,
		17.647058823529413,
		37.5,
		8.333333333333334,
		50,
		0,
		50
	],
	"1-3 Years": [
		20.833333333333332,
		28.571428571428573,
		30,
		50,
		23.529411764705884,
		37.5,
		33.333333333333336,
		16.666666666666668,
		60,
		16.666666666666668
	],
	"3-5 Years": [
		16.666666666666668,
		28.571428571428573,
		20,
		15,
		29.41176470588235,
		12.5,
		50,
		33.333333333333336,
		20,
		0
	],
	"5-10 Years": [
		25,
		14.285714285714286,
		20,
		10,
		23.529411764705884,
		12.5,
		0,
		0,
		20,
		33.333333333333336
	],
	"> 10 years": [
		4.166666666666667,
		7.142857142857143,
		10,
		10,
		5.882352941176471,
		0,
		8.333333333333334,
		0,
		0,
		0
	],
	"other": [
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0
	]
} as const;