// Automatically generated by scenario-matching-question.ts.
// EXPECT MODIFICATIONS TO BE OVERWRITTEN.

export const labels = [
	"Hacked Device",
	"Locked Device",
	"Hacked Acct",
	"Locked Acct",
	"Hacked Social",
	"Locked Social",
	"Hacked Financial",
	"Locked Financial",
	"Hacked Pwds",
	"Locked Pwds"
];
export const data = {
	"Original": [
		10,
		5,
		5,
		0,
		5,
		0,
		15,
		5,
		0,
		0
	],
	"Added": [
		15,
		15,
		0,
		0,
		30,
		10,
		0,
		0,
		5,
		0
	],
	"Not Worst": [
		30,
		15,
		15,
		45,
		15,
		15,
		10,
		20,
		0,
		15
	],
	"Could Happen": [
		35,
		60,
		65,
		45,
		20,
		40,
		65,
		65,
		75,
		60
	],
	"Impossible": [
		10,
		5,
		15,
		10,
		30,
		35,
		10,
		10,
		20,
		25
	]
} as const;