// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/device-bar-chart.ts.

export const labels = [
	"iPhone",
	"Android Phone",
	"Other Phone",
	"iPad",
	"Android Tablet",
	"Other Tablet",
	"Mac",
	"Windows",
	"UNIX",
	"Other Computer"
];
export const data = {
	"Compromised": {
		"Original": [
			1,
			1,
			0,
			0,
			1,
			0,
			0,
			4,
			0,
			0
		],
		"Added": [
			1,
			1,
			0,
			1,
			0,
			0,
			0,
			2,
			0,
			0
		],
		"Not Worst": [
			4,
			3,
			1,
			0,
			0,
			0,
			1,
			1,
			0,
			0
		]
	},
	"Locked Out": {
		"Original": [
			1,
			1,
			0,
			0,
			0,
			0,
			0,
			1,
			0,
			0
		],
		"Added": [
			1,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Not Worst": [
			7,
			2,
			0,
			1,
			0,
			0,
			0,
			1,
			0,
			0
		]
	}
};