// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-recency.ts.

export const labels = [
	"Hacked Device",
	"Locked Device",
	"Hacked Account",
	"Locked Account",
	"Hacked Social",
	"Locked Social",
	"Hacked Financial",
	"Locked Financial",
	"Hacked Passwords",
	"Locked Passwords",
	"Swapped Device/OS",
	"Broken Promise"
];
export const absoluteData = {
	"Within Year": [
		1,
		2,
		0,
		4,
		1,
		1,
		1,
		2,
		1,
		3
	],
	"1-3 Years": [
		2,
		2,
		1,
		5,
		2,
		4,
		3,
		2,
		1,
		0
	],
	"3-5 Years": [
		3,
		1,
		1,
		3,
		2,
		1,
		1,
		1,
		0,
		0
	],
	"5-10 Years": [
		1,
		2,
		0,
		0,
		1,
		0,
		3,
		0,
		0,
		0
	],
	"> 10 years": [
		3,
		1,
		3,
		0,
		0,
		0,
		0,
		2,
		0,
		0
	],
	"Other": [
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0
	]
} as const;
export const percentData = {
	"Within Year": [
		10,
		25,
		0,
		33.333333333333336,
		16.666666666666668,
		16.666666666666668,
		12.5,
		28.571428571428573,
		50,
		100
	],
	"1-3 Years": [
		20,
		25,
		20,
		41.666666666666664,
		33.333333333333336,
		66.66666666666667,
		37.5,
		28.571428571428573,
		50,
		0
	],
	"3-5 Years": [
		30,
		12.5,
		20,
		25,
		33.333333333333336,
		16.666666666666668,
		12.5,
		14.285714285714286,
		0,
		0
	],
	"5-10 Years": [
		10,
		25,
		0,
		0,
		16.666666666666668,
		0,
		37.5,
		0,
		0,
		0
	],
	"> 10 years": [
		30,
		12.5,
		60,
		0,
		0,
		0,
		0,
		28.571428571428573,
		0,
		0
	],
	"Other": [
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0
	]
} as const;