// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/severity-grouped-bar-charts.ts.

export const BarGraphs = {
	"hacked-device-how": {
		"xTitle": "How the device was compromised.",
		"labels": [
			"Compromised Remotely",
			"Stolen",
			"Without Permission",
			"Exceeded Data Permission",
			"Exceeded Other Permission",
			"Regretted Permitting",
			"Other"
		],
		"data": {
			"Original": [
				0,
				1,
				1,
				0,
				0,
				0,
				0
			],
			"Added": [
				1,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				4,
				0,
				2,
				0,
				0,
				0
			]
		}
	},
	"locked-device-how": {
		"xTitle": "How did the participant get locked out of the device",
		"labels": [
			"Forgot PIN/Password",
			"Unrecognized Fingerprint",
			"Unrecognized Face",
			"Recent PIN/Password Change",
			"Software/Update",
			"Broke (impact)",
			"Broke (other)",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				1,
				1,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				4,
				2,
				0,
				0,
				0,
				1,
				0,
				1
			]
		}
	},
	"locked-device-recdat": {
		"xTitle": "Did you recover data from the locked device?",
		"labels": [
			"None",
			"Some",
			"All",
			"Other"
		],
		"data": {
			"Original": [
				2,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				2,
				3,
				0
			]
		}
	},
	"locked-device-dur": {
		"xTitle": "How long did it take to recover?",
		"labels": [
			"Day",
			"Week",
			"Longer",
			"Permanently",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				2,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				2,
				1,
				1,
				2,
				0
			]
		}
	},
	"hacked-acct-how": {
		"xTitle": "How did the participant get locked out of the account",
		"labels": [
			"Knowingly-Abused Access",
			"Unknowingly-Abused Access",
			"Regretted Permitting",
			"Unauthorized Access (known person)",
			"Unauthorized Access (unknown person)",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				1,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				0,
				0,
				0,
				4,
				0
			]
		}
	},
	"hacked-acct-type": {
		"xTitle": "The type of account the participant was locked out of",
		"labels": [
			"Google",
			"Microsoft",
			"Apple",
			"Other"
		],
		"data": {
			"Original": [
				1,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				1,
				1,
				1
			]
		}
	},
	"hacked-acct-dur": {
		"xTitle": "How long did it take to recover their account?",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				1,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				1,
				2,
				0,
				0,
				0
			]
		}
	},
	"locked-acct-how": {
		"xTitle": "How participants' email/drive accounts were locked",
		"labels": [
			"Forgot PIN/Password",
			"PIN/Password No Longer Worked",
			"Phone Number Lost",
			"Device Lost",
			"Password Manager Lost",
			"Paper Lost",
			"Electronic File Lost",
			"Disuse",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				1
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				7,
				1,
				1,
				0,
				0,
				0,
				0,
				0,
				1
			]
		}
	},
	"locked-acct-type": {
		"xTitle": "The type of email/drive account locked",
		"labels": [
			"Google",
			"Microsoft",
			"Apple",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				1
			],
			"Added": [
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				3,
				3,
				4,
				1
			]
		}
	},
	"locked-acct-dur": {
		"xTitle": "How time to recover a locked email/drive account",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				1,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				3,
				2,
				5,
				1,
				0
			]
		}
	},
	"hacked-soc-how": {
		"xTitle": "How participants' social accounts were compromised",
		"labels": [
			"Knowingly-Abused Access",
			"Unknowingly-Abused Access",
			"Regretted Permitting",
			"Unauthorized Access (known person)",
			"Unauthorized Access (unknown person)",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				1,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				0,
				0,
				0,
				4,
				0
			]
		}
	},
	"hacked-soc-type": {
		"xTitle": "The type of social account compromised",
		"labels": [
			"Facebook",
			"Instagram",
			"Twitter/X",
			"SnapChat",
			"WhatsApp",
			"WeChat",
			"Signal",
			"Other"
		],
		"data": {
			"Original": [
				1,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				4,
				0,
				1,
				0,
				0,
				0,
				0
			]
		}
	},
	"hacked-soc-dur": {
		"xTitle": "How time to recover a compromised financial account",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				1,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				3,
				0,
				0,
				1,
				0
			]
		}
	},
	"locked-soc-how": {
		"xTitle": "How participants' social accounts were locked",
		"labels": [
			"Forgot PIN/Password",
			"PIN/Password No Longer Worked",
			"Phone Number Lost",
			"Device Lost",
			"Password Manager Lost",
			"Paper Lost",
			"Electronic File Lost",
			"Disuse",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				4,
				0,
				0,
				1,
				0,
				0,
				0,
				1,
				3
			]
		}
	},
	"locked-soc-type": {
		"xTitle": "The type of social account locked",
		"labels": [
			"Facebook",
			"Instagram",
			"Twitter/X",
			"SnapChat",
			"WhatsApp",
			"WeChat",
			"Signal",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				4,
				1,
				0,
				0,
				0,
				0,
				1
			]
		}
	},
	"locked-soc-dur": {
		"xTitle": "How time to recover a locked social account",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				1,
				2,
				1,
				2,
				0
			]
		}
	},
	"hacked-bank-how": {
		"xTitle": "How participants' social financial were compromised",
		"labels": [
			"Knowingly-Abused Access",
			"Unknowingly-Abused Access",
			"Regretted Permitting",
			"Unauthorized Access (known person)",
			"Unauthorized Access (unknown person)",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				1,
				4,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				0,
				0,
				1,
				2,
				0
			]
		}
	},
	"hacked-bank-type": {
		"xTitle": "The type of financial account compromised",
		"labels": [
			"Credit Card",
			"Credit Union",
			"Retirement",
			"Brokerage",
			"Paypal",
			"Venmo",
			"Cryptocurrency",
			"Bank",
			"Other"
		],
		"data": {
			"Original": [
				1,
				1,
				0,
				0,
				0,
				0,
				0,
				3,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				0,
				0,
				0,
				0,
				0,
				0,
				2,
				0
			]
		}
	},
	"hacked-bank-dur": {
		"xTitle": "How long did it take to recover their bank account?",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				3,
				2,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				3,
				0,
				0,
				0,
				0
			]
		}
	},
	"locked-bank-how": {
		"xTitle": "How participants' financial accounts were locked",
		"labels": [
			"Forgot PIN/Password",
			"PIN/Password No Longer Worked",
			"Phone Number Lost",
			"Device Lost",
			"Password Manager Lost",
			"Paper Lost",
			"Electronic File Lost",
			"Disuse",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				1
			],
			"Not Worst": [
				5,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				1
			]
		}
	},
	"locked-bank-type": {
		"xTitle": "The type of financial account locked",
		"labels": [
			"Credit Card",
			"Credit Union",
			"Retirement",
			"Brokerage",
			"Paypal",
			"Venmo",
			"Cryptocurrency",
			"Bank",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				1,
				0
			],
			"Not Worst": [
				1,
				2,
				0,
				0,
				0,
				0,
				0,
				3,
				0
			]
		}
	},
	"locked-bank-dur": {
		"xTitle": "How time to recover a locked financial account",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				0,
				0
			],
			"Added": [
				0,
				0,
				1,
				0,
				0,
				0
			],
			"Not Worst": [
				0,
				3,
				2,
				1,
				0,
				0
			]
		}
	},
	"swap-device-what": {
		"xTitle": "What went wrong during device/os swap/upgrade",
		"labels": [
			"Device",
			"Software",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				2
			],
			"Added": [
				1,
				0,
				0
			],
			"Not Worst": [
				3,
				3,
				1
			]
		}
	},
	"swap-device-harm": {
		"xTitle": "The was the harm of a device/os swap/upgrade",
		"labels": [
			"Device Data",
			"App Data",
			"Access to Apps/Services",
			"Other"
		],
		"data": {
			"Original": [
				1,
				0,
				0,
				1
			],
			"Added": [
				1,
				0,
				0,
				0
			],
			"Not Worst": [
				3,
				3,
				0,
				1
			]
		}
	},
	"swap-device-dur": {
		"xTitle": "How time to recover after harm from device/os swap/upgrade",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				0,
				0,
				2,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				1,
				0
			],
			"Not Worst": [
				0,
				0,
				1,
				2,
				4,
				0
			]
		}
	},
	"disconnect-how": {
		"xTitle": "What went wrong during disconnect/broken promise",
		"labels": [
			"Unexpected Behavior",
			"Broken Promise",
			"Unreliable",
			"Other"
		],
		"data": {
			"Original": [
				2,
				1,
				2,
				0
			],
			"Added": [
				0,
				0,
				1,
				0
			],
			"Not Worst": [
				0,
				1,
				3,
				0
			]
		}
	},
	"disconnect-harm": {
		"xTitle": "What was the harm of a disconnect/broken promise",
		"labels": [
			"Lost Data",
			"Lost Access/Services",
			"Unavailable",
			"Other"
		],
		"data": {
			"Original": [
				2,
				1,
				2,
				0
			],
			"Added": [
				1,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				1,
				2,
				0
			]
		}
	},
	"disconnect-dur": {
		"xTitle": "How time to recover after harm from disconnect/broken promise",
		"labels": [
			"Never Lost",
			"Within a Day",
			"Within a Week",
			"Eventually",
			"Never Regained",
			"Other"
		],
		"data": {
			"Original": [
				0,
				0,
				2,
				0,
				3,
				0
			],
			"Added": [
				0,
				0,
				0,
				0,
				1,
				0
			],
			"Not Worst": [
				0,
				0,
				2,
				1,
				1,
				0
			]
		}
	}
};