// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/age.ts.
// spell-checker: disable

export const data = [
	{
		"x": 21,
		"y": 13
	},
	{
		"x": 57,
		"y": 3
	},
	{
		"x": 38,
		"y": 2
	},
	{
		"x": 24,
		"y": 1
	},
	{
		"x": 43,
		"y": 5
	},
	{
		"x": 21,
		"y": 3
	},
	{
		"x": 30,
		"y": 2
	},
	{
		"x": 67,
		"y": 0
	},
	{
		"x": 38,
		"y": 5
	}
] as const;
