// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/age.ts.
// spell-checker: disable

export const ageScenarioScatterData = [
	{
		"x": 21,
		"y": 13
	},
	{
		"x": 57,
		"y": 3
	},
	{
		"x": 38,
		"y": 2
	},
	{
		"x": 24,
		"y": 1
	},
	{
		"x": 43,
		"y": 5
	},
	{
		"x": 21,
		"y": 3
	},
	{
		"x": 30,
		"y": 2
	},
	{
		"x": 67,
		"y": 0
	},
	{
		"x": 38,
		"y": 5
	},
	{
		"x": 50,
		"y": 7
	},
	{
		"x": 26,
		"y": 1
	},
	{
		"x": 26,
		"y": 3
	},
	{
		"x": 20,
		"y": 3
	},
	{
		"x": 29,
		"y": 1
	},
	{
		"x": 29,
		"y": 1
	},
	{
		"x": 43,
		"y": 4
	},
	{
		"x": 44,
		"y": 2
	},
	{
		"x": 47,
		"y": 5
	},
	{
		"x": 27,
		"y": 2
	},
	{
		"x": 19,
		"y": 3
	},
	{
		"x": 20,
		"y": 8
	},
	{
		"x": 23,
		"y": 6
	},
	{
		"x": 32,
		"y": 3
	},
	{
		"x": 34,
		"y": 9
	},
	{
		"x": 50,
		"y": 13
	}
] as const;
export const agePercentPoints = [
	{
		"x": 19,
		"y": 4
	},
	{
		"x": 20,
		"y": 8
	},
	{
		"x": 21,
		"y": 8
	},
	{
		"x": 23,
		"y": 4
	},
	{
		"x": 24,
		"y": 4
	},
	{
		"x": 26,
		"y": 8
	},
	{
		"x": 27,
		"y": 4
	},
	{
		"x": 29,
		"y": 8
	},
	{
		"x": 30,
		"y": 4
	},
	{
		"x": 32,
		"y": 4
	},
	{
		"x": 34,
		"y": 4
	},
	{
		"x": 38,
		"y": 8
	},
	{
		"x": 43,
		"y": 8
	},
	{
		"x": 44,
		"y": 4
	},
	{
		"x": 47,
		"y": 4
	},
	{
		"x": 50,
		"y": 8
	},
	{
		"x": 57,
		"y": 4
	},
	{
		"x": 67,
		"y": 4
	}
] as const;
