// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/harm-focused-likert.ts.
// spell-checker: disable

	export const labels = [
	"Lost Photos",
	"Lost Emails",
	"Mental Health"
] as const;
	export const counts = {
	"1": [
		1,
		2,
		0
	],
	"2": [
		1,
		0,
		0
	],
	"3": [
		0,
		2,
		2
	],
	"4": [
		0,
		1,
		1
	],
	"5": [
		3,
		1,
		7
	],
	"6": [
		1,
		0,
		1
	],
	"7": [
		1,
		1,
		0
	],
	"No loss": [
		0,
		0,
		0
	]
} as const;
	export const percentsOfResponses = {
	"1": [
		4,
		8,
		0
	],
	"2": [
		4,
		0,
		0
	],
	"3": [
		0,
		8,
		8
	],
	"4": [
		0,
		4,
		4
	],
	"5": [
		12,
		4,
		28
	],
	"6": [
		4,
		0,
		4
	],
	"7": [
		4,
		4,
		0
	],
	"No loss": [
		0,
		0,
		0
	]
} as const;
	export const percentsOfAnswered = {
	"1": [
		14.285714285714286,
		28.571428571428573,
		0
	],
	"2": [
		14.285714285714286,
		0,
		0
	],
	"3": [
		0,
		28.571428571428573,
		18.181818181818183
	],
	"4": [
		0,
		14.285714285714286,
		9.090909090909092
	],
	"5": [
		42.857142857142854,
		14.285714285714286,
		63.63636363636363
	],
	"6": [
		14.285714285714286,
		0,
		9.090909090909092
	],
	"7": [
		14.285714285714286,
		14.285714285714286,
		0
	],
	"No loss": [
		0,
		0,
		0
	]
} as const;
