// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.
// spell-checker: disable

export const pairedScenarioLabels = [
	"Device",
	"Account",
	"Social",
	"Bank",
	"Passwords"
];
export const compromisedScenarioData = {
	"Original": [
		4,
		8,
		16,
		8,
		4
	],
	"Revised": [
		20,
		4,
		0,
		16,
		8
	],
	"Not Worst": [
		8,
		4,
		8,
		0,
		12
	],
	"Could Happen": [
		56,
		56,
		48,
		64,
		60
	],
	"Impossible": [
		12,
		28,
		28,
		12,
		16
	]
};
export const lockedOutScenarioData = {
	"Original": [
		16,
		0,
		12,
		8,
		8
	],
	"Revised": [
		0,
		8,
		0,
		4,
		4
	],
	"Not Worst": [
		20,
		20,
		20,
		16,
		20
	],
	"Could Happen": [
		48,
		52,
		48,
		56,
		48
	],
	"Impossible": [
		16,
		20,
		20,
		16,
		20
	]
};
export const unpairedScenarioLabels = [
	"Replaced Device/OS",
	"Broken Promise",
	"Abuse",
	"Lost Photos",
	"Lost Emails",
	"Mental Health"
];
export const unpairedScenarioData = {
	"Original": [
		8,
		28,
		25,
		20,
		27.77777777777778,
		58.8235294117647
	],
	"Revised": [
		16,
		12,
		0,
		13.333333333333334,
		5.555555555555555,
		0
	],
	"Not Worst": [
		20,
		36,
		0,
		13.333333333333334,
		11.11111111111111,
		5.882352941176471
	],
	"Could Happen": [
		44,
		24,
		45.833333333333336,
		33.333333333333336,
		22.22222222222222,
		29.41176470588235
	],
	"Impossible": [
		12,
		0,
		29.166666666666668,
		20,
		33.333333333333336,
		5.882352941176471
	]
};
export const compromisedAndUnpairedScenarioData = {
	"Original": [
		4,
		8,
		16,
		8,
		4,
		8,
		28,
		25,
		20,
		27.77777777777778,
		58.8235294117647
	],
	"Revised": [
		20,
		4,
		0,
		16,
		8,
		16,
		12,
		0,
		13.333333333333334,
		5.555555555555555,
		0
	],
	"Not Worst": [
		8,
		4,
		8,
		0,
		12,
		20,
		36,
		0,
		13.333333333333334,
		11.11111111111111,
		5.882352941176471
	],
	"Could Happen": [
		56,
		56,
		48,
		64,
		60,
		44,
		24,
		45.833333333333336,
		33.333333333333336,
		22.22222222222222,
		29.41176470588235
	],
	"Impossible": [
		12,
		28,
		28,
		12,
		16,
		12,
		0,
		29.166666666666668,
		20,
		33.333333333333336,
		5.882352941176471
	]
};