// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/lume-data/summary-statistics.ts.
// spell-checker: disable

export const data = {
	"numberOfParticipants": 10
} as const;