// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by graph-data/account-type.ts.

export const labels = [
	"Apple",
	"Google",
	"Microsoft",
	"Other"
];
export const data = {
	"hacked": [
		0,
		6,
		3,
		0
	],
	"locked": [
		3,
		11,
		4,
		1
	]
} as const;