// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by graph-data/account-type.ts.

export const emailAccount = {
	labels: [
		"Apple",
		"Google",
		"Microsoft",
		"Other"
],
	data: {
		"compromised": [
				0,
				6,
				3,
				0
		],
		"lockedOut": [
				3,
				11,
				4,
				1
		]
}};

export const socialAccount = {
	labels: [
		"Facebook",
		"Instagram",
		"Twitter/X",
		"SnapChat",
		"WhatsApp",
		"WeChat",
		"Signal",
		"Other"
],
	data: {
		"compromised": [
				9,
				3,
				1,
				2,
				1,
				0,
				0,
				1
		],
		"lockedOut": [
				4,
				1,
				0,
				2,
				1,
				0,
				0,
				0
		]
}};

