// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.

export const labels = [
	"Device",
	"Account",
	"Social",
	"Bank",
	"Passwords"
];
export const data = {
	"Compromised": {
		"Original": [
			16,
			6,
			4,
			14,
			2
		],
		"Added": [
			6,
			4,
			14,
			2,
			4
		],
		"Not Worst": [
			26,
			10,
			16,
			8,
			4
		],
		"Could Happen": [
			40,
			64,
			42,
			68,
			72
		],
		"Impossible": [
			12,
			16,
			24,
			8,
			18
		]
	},
	"Locked Out": {
		"Original": [
			6,
			6,
			2,
			2,
			2
		],
		"Added": [
			6,
			0,
			4,
			2,
			0
		],
		"Not Worst": [
			18,
			34,
			10,
			8,
			10
		],
		"Could Happen": [
			58,
			48,
			58,
			72,
			66
		],
		"Impossible": [
			12,
			12,
			26,
			16,
			22
		]
	}
};