// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.

export const labels = [
	"Hacked Device",
	"Locked Device",
	"Hacked Account",
	"Locked Account",
	"Hacked Social",
	"Locked Social",
	"Hacked Financial",
	"Locked Financial",
	"Hacked Passwords",
	"Locked Passwords"
];
export const data = {
	"Original": [
		16,
		6,
		6,
		6,
		4,
		2,
		14,
		2,
		2,
		2
	],
	"Added": [
		6,
		6,
		4,
		0,
		14,
		4,
		2,
		2,
		4,
		0
	],
	"Not Worst": [
		26,
		18,
		10,
		34,
		16,
		10,
		8,
		8,
		4,
		10
	],
	"Could Happen": [
		40,
		58,
		64,
		48,
		42,
		58,
		68,
		72,
		72,
		66
	],
	"Impossible": [
		12,
		12,
		16,
		12,
		24,
		26,
		8,
		16,
		18,
		22
	]
} as const;