// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/severity-grouped-bar-charts.ts.

export const BarGraphs = {
	"hacked-device-how": {
		"xTitle": "How the device was compromised.",
		"labels": [
			"Compromised Remotely",
			"Stolen",
			"Without Permission",
			"Exceeded Data Permission",
			"Exceeded Other Permission",
			"Regretted Permitting",
			"Other"
		],
		"data": {
			"Original": [
				3,
				0,
				2,
				3,
				0,
				0,
				0
			],
			"Added": [
				2,
				1,
				0,
				0,
				0,
				0,
				0
			],
			"Not Worst": [
				1,
				2,
				8,
				0,
				0,
				1,
				0
			]
		}
	},
	"locked-device-how": {
		"xTitle": "How did the user get locked out of the device",
		"labels": [
			"Forgot PIN/Password",
			"Unrecognized Fingerprint",
			"Unrecognized Face",
			"Recent PIN/Password Change",
			"Software/Update",
			"Broke (impact)",
			"Broke (other)",
			"Other"
		],
		"data": {
			"Original": [
				1,
				0,
				1,
				0,
				1,
				0,
				0,
				0
			],
			"Added": [
				2,
				1,
				1,
				1,
				0,
				2,
				1,
				0
			],
			"Not Worst": [
				6,
				1,
				0,
				0,
				0,
				1,
				0,
				2
			]
		}
	},
	"locked-device-recdat": {
		"xTitle": "Did you recover data from the locked device?",
		"labels": [
			"None",
			"Some",
			"All",
			"Other"
		],
		"data": {
			"Original": [
				0,
				2,
				1,
				0
			],
			"Added": [
				1,
				2,
				0,
				0
			],
			"Not Worst": [
				3,
				1,
				5,
				0
			]
		}
	},
	"locked-device-rec": {
		"xTitle": "How long did it take to recover?",
		"labels": [
			"Day",
			"Week",
			"Longer",
			"Permanently",
			"Other"
		],
		"data": {
			"Original": [
				0,
				2,
				1,
				0,
				0
			],
			"Added": [
				0,
				0,
				1,
				2,
				0
			],
			"Not Worst": [
				2,
				4,
				1,
				2,
				0
			]
		}
	}
};