// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/lume-data/summary-statistics.ts.

export const data = {
	"numberOfParticipants": 24
} as const;