// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/age.ts.
// spell-checker: disable

export const ageScenarioScatterData = [
	{
		"x": 38,
		"y": 1
	},
	{
		"x": 52,
		"y": 6
	},
	{
		"x": 30,
		"y": 4
	},
	{
		"x": 31,
		"y": 3
	},
	{
		"x": 44,
		"y": 3
	},
	{
		"x": 41,
		"y": 10
	},
	{
		"x": 41,
		"y": 4
	},
	{
		"x": 36,
		"y": 7
	},
	{
		"x": 32,
		"y": 5
	},
	{
		"x": 53,
		"y": 5
	},
	{
		"x": 35,
		"y": 9
	},
	{
		"x": 32,
		"y": 2
	},
	{
		"x": 31,
		"y": 3
	},
	{
		"x": 56,
		"y": 3
	},
	{
		"x": 20,
		"y": 3
	},
	{
		"x": 57,
		"y": 4
	},
	{
		"x": 32,
		"y": 5
	},
	{
		"x": 43,
		"y": 8
	},
	{
		"x": 44,
		"y": 3
	},
	{
		"x": 28,
		"y": 4
	}
] as const;
export const agePercentPoints = [
	{
		"x": 20,
		"y": 5
	},
	{
		"x": 28,
		"y": 5
	},
	{
		"x": 30,
		"y": 5
	},
	{
		"x": 31,
		"y": 10
	},
	{
		"x": 32,
		"y": 15
	},
	{
		"x": 35,
		"y": 5
	},
	{
		"x": 36,
		"y": 5
	},
	{
		"x": 38,
		"y": 5
	},
	{
		"x": 41,
		"y": 10
	},
	{
		"x": 43,
		"y": 5
	},
	{
		"x": 44,
		"y": 10
	},
	{
		"x": 52,
		"y": 5
	},
	{
		"x": 53,
		"y": 5
	},
	{
		"x": 56,
		"y": 5
	},
	{
		"x": 57,
		"y": 5
	}
] as const;
