// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/demographics.ts.
// spell-checker: disable

export const gender = {
	"labels": [
		"Male",
		"Female",
		"Non-binary/third",
		"Self-describe",
		"Prefer not to say"
	],
	"tallies": {
		"_totalResponses": 29,
		"Female": 12,
		"_totalAnswered": 29,
		"Male": 15,
		"Non-binary/third": 1,
		"Prefer not to say": 1
	},
	"data": [
		15,
		12,
		1,
		0,
		1
	]
} as const;
export const genderPercent = {
	"labels": [
		"Male",
		"Female",
		"Non-binary/third",
		"Self-describe",
		"Prefer not to say"
	],
	"tallies": {
		"_totalResponses": 100,
		"Female": 41.37931034482759,
		"Male": 51.724137931034484,
		"Non-binary/third": 3.4482758620689653,
		"Prefer not to say": 3.4482758620689653
	},
	"data": [
		51.724137931034484,
		41.37931034482759,
		3.4482758620689653,
		0,
		3.4482758620689653
	]
} as const;
export const education = {
	"labels": [
		"< High School",
		"High School",
		"Some College",
		"Associate",
		"Bachelor's",
		"Master's",
		"Professional",
		"Doctoral",
		"Decline to Answer"
	],
	"tallies": {
		"_totalResponses": 29,
		"Some College": 7,
		"_totalAnswered": 29,
		"Bachelor's": 6,
		"Doctoral": 1,
		"High School": 6,
		"Associate": 4,
		"Master's": 3,
		"Professional": 1,
		"< High School": 1
	},
	"data": [
		1,
		6,
		7,
		4,
		6,
		3,
		1,
		1,
		0
	]
} as const;
export const educationPercent = {
	"labels": [
		"< High School",
		"High School",
		"Some College",
		"Associate",
		"Bachelor's",
		"Master's",
		"Professional",
		"Doctoral",
		"Decline to Answer"
	],
	"tallies": {
		"_totalResponses": 100,
		"Some College": 24.137931034482758,
		"Bachelor's": 20.689655172413794,
		"Doctoral": 3.4482758620689653,
		"High School": 20.689655172413794,
		"Associate": 13.793103448275861,
		"Master's": 10.344827586206897,
		"Professional": 3.4482758620689653,
		"< High School": 3.4482758620689653
	},
	"data": [
		3.4482758620689653,
		20.689655172413794,
		24.137931034482758,
		13.793103448275861,
		20.689655172413794,
		10.344827586206897,
		3.4482758620689653,
		3.4482758620689653,
		0
	]
} as const;
