// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/demographics.ts.
// spell-checker: disable

export const gender = {
	"labels": [
		"Male",
		"Female",
		"Non-binary/third",
		"Self-describe",
		"Prefer not to say"
	],
	"tallies": {
		"_totalResponses": 20,
		"Female": 8,
		"_totalAnswered": 20,
		"Male": 10,
		"Non-binary/third": 1,
		"Prefer not to say": 1
	},
	"data": [
		10,
		8,
		1,
		0,
		1
	]
} as const;
export const genderPercent = {
	"labels": [
		"Male",
		"Female",
		"Non-binary/third",
		"Self-describe",
		"Prefer not to say"
	],
	"tallies": {
		"_totalResponses": 100,
		"Female": 40,
		"Male": 50,
		"Non-binary/third": 5,
		"Prefer not to say": 5
	},
	"data": [
		50,
		40,
		5,
		0,
		5
	]
} as const;
export const education = {
	"labels": [
		"< High School",
		"High School",
		"Some College",
		"Associate",
		"Bachelor's",
		"Master's",
		"Professional",
		"Doctoral",
		"Decline to Answer"
	],
	"tallies": {
		"_totalResponses": 20,
		"Some College": 4,
		"_totalAnswered": 20,
		"Bachelor's": 4,
		"Doctoral": 1,
		"High School": 4,
		"Associate": 2,
		"Master's": 3,
		"Professional": 1,
		"< High School": 1
	},
	"data": [
		1,
		4,
		4,
		2,
		4,
		3,
		1,
		1,
		0
	]
} as const;
export const educationPercent = {
	"labels": [
		"< High School",
		"High School",
		"Some College",
		"Associate",
		"Bachelor's",
		"Master's",
		"Professional",
		"Doctoral",
		"Decline to Answer"
	],
	"tallies": {
		"_totalResponses": 100,
		"Some College": 20,
		"Bachelor's": 20,
		"Doctoral": 5,
		"High School": 20,
		"Associate": 10,
		"Master's": 15,
		"Professional": 5,
		"< High School": 5
	},
	"data": [
		5,
		20,
		20,
		10,
		20,
		15,
		5,
		5,
		0
	]
} as const;
