// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/harm-focused-likert.ts.
// spell-checker: disable

	export const labels = [
	"Lost Photos",
	"Lost Emails",
	"Mental Health"
] as const;
	export const counts = {
	"1": [
		0,
		0,
		1
	],
	"2": [
		1,
		1,
		1
	],
	"3": [
		0,
		2,
		0
	],
	"4": [
		0,
		0,
		2
	],
	"5": [
		4,
		4,
		6
	],
	"6": [
		3,
		1,
		3
	],
	"7": [
		2,
		0,
		2
	],
	"No loss": [
		0,
		0,
		0
	]
} as const;
	export const percentsOfResponses = {
	"1": [
		0,
		0,
		5
	],
	"2": [
		5,
		5,
		5
	],
	"3": [
		0,
		10,
		0
	],
	"4": [
		0,
		0,
		10
	],
	"5": [
		20,
		20,
		30
	],
	"6": [
		15,
		5,
		15
	],
	"7": [
		10,
		0,
		10
	],
	"No loss": [
		0,
		0,
		0
	]
} as const;
	export const percentsOfAnswered = {
	"1": [
		0,
		0,
		6.666666666666667
	],
	"2": [
		10,
		12.5,
		6.666666666666667
	],
	"3": [
		0,
		25,
		0
	],
	"4": [
		0,
		0,
		13.333333333333334
	],
	"5": [
		40,
		50,
		40
	],
	"6": [
		30,
		12.5,
		20
	],
	"7": [
		20,
		0,
		13.333333333333334
	],
	"No loss": [
		0,
		0,
		0
	]
} as const;
