// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.
// spell-checker: disable

export const pairedScenarioLabels = [
	"Device",
	"Account",
	"Social",
	"Bank",
	"Passwords"
];
export const compromisedScenarioData = {
	"Original": [
		0,
		10,
		25,
		35,
		10
	],
	"Revised": [
		15,
		5,
		0,
		0,
		5
	],
	"Not Worst": [
		15,
		10,
		15,
		5,
		20
	],
	"Could Happen": [
		45,
		65,
		45,
		50,
		35
	],
	"Impossible": [
		25,
		10,
		15,
		10,
		30
	]
};
export const lockedOutScenarioData = {
	"Original": [
		10,
		10,
		15,
		15,
		10
	],
	"Revised": [
		10,
		5,
		0,
		0,
		0
	],
	"Not Worst": [
		10,
		20,
		15,
		15,
		25
	],
	"Could Happen": [
		50,
		50,
		40,
		50,
		25
	],
	"Impossible": [
		20,
		15,
		30,
		20,
		40
	]
};
export const unpairedScenarioLabels = [
	"Replaced Device/OS",
	"Broken Promise",
	"Abuse",
	"Lost Photos",
	"Lost Emails",
	"Mental Health"
];
export const unpairedScenarioData = {
	"Original": [
		15,
		35,
		35,
		35.714285714285715,
		15.789473684210526,
		88.23529411764706
	],
	"Revised": [
		0,
		0,
		5,
		14.285714285714286,
		5.2631578947368425,
		0
	],
	"Not Worst": [
		25,
		10,
		5,
		21.428571428571427,
		26.31578947368421,
		0
	],
	"Could Happen": [
		35,
		25,
		20,
		28.571428571428573,
		42.10526315789474,
		0
	],
	"Impossible": [
		25,
		30,
		35,
		0,
		10.526315789473685,
		11.764705882352942
	]
};
export const compromisedAndUnpairedScenarioData = {
	"Original": [
		0,
		10,
		25,
		35,
		10,
		15,
		35,
		35,
		35.714285714285715,
		15.789473684210526,
		88.23529411764706
	],
	"Revised": [
		15,
		5,
		0,
		0,
		5,
		0,
		0,
		5,
		14.285714285714286,
		5.2631578947368425,
		0
	],
	"Not Worst": [
		15,
		10,
		15,
		5,
		20,
		25,
		10,
		5,
		21.428571428571427,
		26.31578947368421,
		0
	],
	"Could Happen": [
		45,
		65,
		45,
		50,
		35,
		35,
		25,
		20,
		28.571428571428573,
		42.10526315789474,
		0
	],
	"Impossible": [
		25,
		10,
		15,
		10,
		30,
		25,
		30,
		35,
		0,
		10.526315789473685,
		11.764705882352942
	]
};