// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/age.ts.
// spell-checker: disable

export const data = [
	{
		"x": 35,
		"y": 3
	},
	{
		"x": 34,
		"y": 3
	},
	{
		"x": 52,
		"y": 4
	},
	{
		"x": 39,
		"y": 4
	},
	{
		"x": 32,
		"y": 3
	},
	{
		"x": 26,
		"y": 4
	},
	{
		"x": 35,
		"y": 1
	},
	{
		"x": 26,
		"y": 3
	},
	{
		"x": 36,
		"y": 5
	},
	{
		"x": 31,
		"y": 4
	},
	{
		"x": 35,
		"y": 6
	},
	{
		"x": 24,
		"y": 2
	},
	{
		"x": 23,
		"y": 2
	},
	{
		"x": 46,
		"y": 1
	},
	{
		"x": 30,
		"y": 2
	},
	{
		"x": 38,
		"y": 2
	},
	{
		"x": 61,
		"y": 6
	},
	{
		"x": 42,
		"y": 6
	},
	{
		"x": 30,
		"y": 5
	},
	{
		"x": 41,
		"y": 2
	}
] as const;
