// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/harm-focused-likert.ts.
// spell-checker: disable

	export const labels = [
	"Lost Photos",
	"Lost Emails"
];
	export const counts = {
	"1": [
		0,
		1
	],
	"2": [
		3,
		1
	],
	"3": [
		4,
		5
	],
	"4": [
		2,
		1
	],
	"5": [
		3,
		1
	],
	"6": [
		3,
		1
	],
	"7": [
		2,
		1
	],
	"No loss": [
		0,
		0
	]
};
	export const percentsOfResponses = {
	"1": [
		0,
		5
	],
	"2": [
		15,
		5
	],
	"3": [
		20,
		25
	],
	"4": [
		10,
		5
	],
	"5": [
		15,
		5
	],
	"6": [
		15,
		5
	],
	"7": [
		10,
		5
	],
	"No loss": [
		0,
		0
	]
};
	export const percentsOfAnswered = {
	"1": [
		0,
		9.090909090909092
	],
	"2": [
		17.647058823529413,
		9.090909090909092
	],
	"3": [
		23.529411764705884,
		45.45454545454545
	],
	"4": [
		11.764705882352942,
		9.090909090909092
	],
	"5": [
		17.647058823529413,
		9.090909090909092
	],
	"6": [
		17.647058823529413,
		9.090909090909092
	],
	"7": [
		11.764705882352942,
		9.090909090909092
	],
	"No loss": [
		0,
		0
	]
};
