// DO NOT MODIFY (your modifications will be overwritten)
// This file is automatically (re-)generated by generate/graph-data/scenario-matching-question.ts.
// spell-checker: disable

export const pairedScenarioLabels = [
	"Device",
	"Account",
	"Social",
	"Bank",
	"Passwords"
];
export const compromisedScenarioData = {
	"Original": [
		10,
		0,
		10,
		15,
		15
	],
	"Added": [
		0,
		5,
		0,
		5,
		0
	],
	"Not Worst": [
		15,
		10,
		10,
		0,
		5
	],
	"Could Happen": [
		65,
		65,
		60,
		80,
		65
	],
	"Impossible": [
		10,
		20,
		20,
		0,
		15
	]
};
export const lockedOutScenarioData = {
	"Original": [
		0,
		0,
		0,
		0,
		0
	],
	"Added": [
		5,
		0,
		5,
		5,
		5
	],
	"Not Worst": [
		30,
		45,
		20,
		15,
		5
	],
	"Could Happen": [
		45,
		35,
		50,
		65,
		65
	],
	"Impossible": [
		20,
		20,
		25,
		15,
		25
	]
};
export const unpairedScenarioLabels = [
	"Replaced Device/OS",
	"Broken Promise"
];
export const unpairedScenarioData = {
	"Original": [
		10,
		20
	],
	"Added": [
		0,
		0
	],
	"Not Worst": [
		35,
		40
	],
	"Could Happen": [
		45,
		40
	],
	"Impossible": [
		10,
		0
	]
};
export const compromisedAndUnpairedScenarioData = {
	"Original": [
		10,
		0,
		10,
		15,
		15,
		10,
		20
	],
	"Added": [
		0,
		5,
		0,
		5,
		0,
		0,
		0
	],
	"Not Worst": [
		15,
		10,
		10,
		0,
		5,
		35,
		40
	],
	"Could Happen": [
		65,
		65,
		60,
		80,
		65,
		45,
		40
	],
	"Impossible": [
		10,
		20,
		20,
		0,
		15,
		10,
		0
	]
};